"""add shipping fields to orders

Revision ID: a524ed91fd40
Revises: 16c2d829b3fa
Create Date: 2026-07-11 10:18:19.946158

"""
from alembic import op
import sqlalchemy as sa


revision = 'a524ed91fd40'
down_revision = '16c2d829b3fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('shipping_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_email')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_address')
    # ### end Alembic commands ###
